### ISSUE TITLE
Issues with PDF output

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-m3d#8]
(Originally from here: https://github.com/riboseinc/metanorma-m3d/issues/7#issuecomment-417839978)

Remaining issues with PDF:

1. M3AAWG logo is squished sideways
2. The "link" icons next to section headers should not be shown
3. Missing ToC
4. Title page copyright year 2018, at the end colophon says 2017.
5. There are a number of spurious elements on the title page:

```
Updated August 2011, Version draft (should be something here?) 
(what's this?) TC ISO/TC 154PROCESSES, DATA ELEMENTS AND DOCUMENTS IN COMMERCE, INDUSTRY AND ADMINISTRATION
(what's this?) RIBOSE REPORT
(what's this? is this in contrast with DRAFT?) PUBLISHED
```

**Comment by opoudjis** [comment]
1. Squishing sideways is inherited from HTML; fixed by setting height = auto for the logo.

2. requires suppressing the anchor.js Javascript from all instances of PDF. That means a metanorma-wide change in how scripts.html is invoked.

**Comment by opoudjis** [comment]
4. Fixed in colophon code, HTML and PDF.

**Comment by opoudjis** [comment]
5. `:draft` was used for both the label and the draft version; so the document was spuriously being reported as being having a draft number of "draft". Fixed in isodoc.

Removed "Ribose" before document type

PUBLISHED is the document status, and is indeed in contrast with draft.

Restricted committee to bibdata, not to first technical-committee found in the text.
